# Generated by Django 3.2.4 on 2021-06-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_departamento', models.CharField(default='--', max_length=2, unique=True)),
                ('nombre_departamento', models.CharField(default='--', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_municipio', models.CharField(default='--', max_length=100)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.departamento', to_field='id_departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre_persona', models.CharField(default='--', max_length=100)),
                ('segundo_nombre_persona', models.CharField(default='--', max_length=100)),
                ('primer_apellido_persona', models.CharField(default='--', max_length=100)),
                ('segundo_apellido_persona', models.CharField(default='--', max_length=100)),
                ('tercer_apellido_persona', models.CharField(default='--', max_length=100)),
                ('departamento_de_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.departamento', to_field='id_departamento')),
                ('municipio_de_nacimiento', models.ForeignKey(limit_choices_to={'id_departamento': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.departamento', to_field='id_departamento')}, on_delete=django.db.models.deletion.CASCADE, to='vacunacion.municipio')),
            ],
        ),
    ]
