# Generated by Django 3.2.4 on 2021-06-23 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='--', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='--', max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dui', models.CharField(max_length=10, unique=True)),
                ('fecha_de_nacimiento', models.DateField()),
                ('departamento_de_nacimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacunacion.departamento')),
                ('municipio_de_nacimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacunacion.municipio')),
            ],
        ),
    ]
