# Generated by Django 3.2.4 on 2021-06-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='codigo_departamento',
            field=models.CharField(default='--', max_length=2),
        ),
    ]
