# Generated by Django 3.2.4 on 2021-06-16 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('vacunacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
