# Generated by Django 3.2.4 on 2021-06-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacunacion', '0007_alter_persona_municipio_de_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='id_departamento',
            new_name='codigo_departamento',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='nombre_departamento',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='nombre_municipio',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='primer_apellido_persona',
            new_name='primer_apellido',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='primer_nombre_persona',
            new_name='primer_nombre',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='segundo_apellido_persona',
            new_name='segundo_apellido',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='segundo_nombre_persona',
            new_name='segundo_nombre',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='tercer_apellido_persona',
            new_name='tercer_apellido',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='id_departamento',
        ),
        migrations.AddField(
            model_name='municipio',
            name='codigo_departamento',
            field=models.ForeignKey(default='--', on_delete=django.db.models.deletion.CASCADE,
                                    to='vacunacion.departamento', to_field='codigo_departamento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='municipio_de_nacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.municipio'),
        ),
    ]
