# Generated by Django 3.2.4 on 2021-06-16 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('vacunacion', '0009_alter_municipio_codigo_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='primer_apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='primer_nombre',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='segundo_nombre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tercer_apellido',
        ),
    ]
