# Generated by Django 3.2.4 on 2021-06-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0010_auto_20210616_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombres',
        ),
    ]
