# Generated by Django 3.2.4 on 2021-06-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0011_auto_20210618_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='dui',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombres',
            field=models.CharField(default='---', max_length=100),
        ),
    ]
