# Generated by Django 3.2.4 on 2021-06-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0012_auto_20210619_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
