# Generated by Django 3.2.4 on 2021-06-21 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0013_delete_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacunacionPersona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=100)),
                ('dui', models.CharField(max_length=10)),
                ('fecha_de_nacimiento', models.DateField()),
                ('nombres', models.CharField(max_length=100)),
                ('departamento_de_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vacunacion.departamento')),
                ('municipio_de_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vacunacion.municipio')),
            ],
        ),
    ]
