# Generated by Django 3.2.4 on 2021-06-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0014_vacunacionpersona'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacunacionPersona',
            new_name='Persona',
        ),
    ]
