# Generated by Django 3.2.4 on 2021-06-22 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0015_rename_vacunacionpersona_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='municipio_de_nacimiento',
            field=models.ForeignKey(limit_choices_to={'departamento_de_nacimiento': models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vacunacion.departamento')}, on_delete=django.db.models.deletion.DO_NOTHING, to='vacunacion.municipio'),
        ),
    ]
