# Generated by Django 3.2.4 on 2021-06-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0016_alter_persona_municipio_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='municipio_de_nacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vacunacion.municipio'),
        ),
    ]
