# Generated by Django 3.2.4 on 2021-06-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0017_alter_persona_municipio_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dui',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
